/*
 * Solar_Tracker.asm
 *
 *  Created: 08/06/2016 07:45:11 p.m.
 *   Author: Agustín Picard, Joaquin Ulloa, Mauro Giordano
 */ 

.include "m88def.inc"   	;Incluye los nombres de los registros del micro
.include "Solar_Tracker.inc"
.include "MESSAGES.inc"
.include "avr_macros.inc"	;Incluye los macros
.listmac					;Permite que se expandan las macros en el listado

.CSEG
.ORG 0x0000
RJMP SETUP	

.ORG	INT0addr
RJMP	ISR_INT0

.ORG	URXCaddr		; USART, Rx Complete
RJMP	ISR_RX_USART_COMPLETA
	
.ORG	UDREaddr		; USART Data Register Empty
RJMP	ISR_REG_USART_VACIO

.ORG	OVF1addr
RJMP	ISR_TIMER_1_OV

;-------------------------------SETUP--------------------------------------------
.ORG	INT_VECTORS_SIZE
SETUP:
	LDI AUX,LOW(RAMEND)
	OUT SPL,AUX
	LDI	AUX,HIGH(RAMEND)
	OUT SPH,AUX

	RCALL INT_EXT_INIT
	RCALL BATTERY_INIT
	RCALL SOLAR_PANEL_INIT
	RCALL ADC_INIT			;TIENE QUE ESTAR EN "ADC.inc"
RJMP PRUEBA
	RCALL PWM_INIT			;TIENE QUE ESTAR EN "PWM.inc"
	RCALL SERIAL_PORT_INIT	;TIENE QUE ESTAR EN "SERIAL_PORT.inc"
	RCALL LDRS_INIT
	RCALL LIGHT_TURN_OFF	;TIENE QUE ESTAR EN "LIGHT.inc"
	RCALL MOTORS_INIT
	RCALL BT_DISCONNECT		;[FLAG=0xFF]: ESTA CONECTADO A BT. [FLAG=0x00]: NO ESTA CONECTADO A BT.
	SEI
	RJMP PRUEBA
;--------------------------------------------------------------------------------
PRUEBA:
		RCALL	READ_V_SOLAR_PANEL				;PARA VER SI ES DE DIA O NOCHE, MIDO LA TENSION DEL PANEL SOLAR.
		RCALL	CHECK_IF_SOLAR_PANEL_MINIMUM	;[CARRY=1]: ES DE DIA. [CARRY=0]: ES DE NOCHE.
		BRCC	AT_NIGHT
		RCALL	DELAY_500ms
RJMP PRUEBA
;-------------------------------PROGRAMA_PRINCIPAL-------------------------------
MAIN:	
	;MEDIR BATERIA 
		RCALL	READ_V_BATTERY					;MIDO LA BATERIA
		RCALL	CHECK_IF_BATTERY_MINIMUM		;[CARRY=1]: BATTERY LOW. [CARRY=0]: BATTERY OK
		BRCC	SLEEP_MODE
		RCALL	INDICATE_BATTERY_OK
	;¿DIA O NOCHE?
		RCALL	READ_V_SOLAR_PANEL				;PARA VER SI ES DE DIA O NOCHE, MIDO LA TENSION DEL PANEL SOLAR.
		RCALL	CHECK_IF_SOLAR_PANEL_CONNECTED	;[CARRY=1]: HAY PANEL. [CARRY=0]: NO HAY PANEL.
		BRCC	NO_SOLAR_PANEL_CONNECTED
		RCALL	CHECK_IF_SOLAR_PANEL_MINIMUM	;[CARRY=1]: ES DE DIA. [CARRY=0]: ES DE NOCHE.
		BRCC	AT_NIGHT
;SI ESTOY ACA YA TENGO BATERIA SUFICIENTE, ES DE DIA.
		RCALL	LIGHT_TURN_OFF
		RCALL	INDICATE_SOLAR_PANEL_OK
;PRENDER EL TIMER, LA INTERRUPCION DEL ADC MANDAR A SLEEP.
		RCALL	READ_LDRS						;LEE LOS LDR'S Y LOS MANDA A RAM.
		BRCC	SLEEP_MODE						;[CARRY=1]: HIZO PROMEDIO, NO SE VA A SLEEP. [CARRY=0]: NO HIZO PROMEDIO, SE VA A SLEEP.
		RCALL	ORIENTATE_SOLAR_PANEL			;HAY QUE RESOLVER ESTO TODAVIA.

;HACE UN LOOP CON LOS VALORES MEDIDOS Y MOVER A OJO.		
SLEEP_MODE:
;HAY QUE HACER COSAS ANTES DE IR A SLEEP, COMO APAGAR EL ADC Y NO SE QUE MAS [COMO EL PWM DE LOS MOTORES]
;SALIR DE SLEEP: EN UN TIEMPO t [TIEMPO ENTRE MEDICION Y MEDICION].
/*		INPUT AUX,SMCR
		ANDI AUX,(~(1<<SM2)|(1<<SM1)|(1<<SM0)|(1<<SE))
		ORI AUX,((0<<SM2)|(0<<SM1)|(0<<SM0)|(1<<SE))	;SETEO EL MODO IDLE.
		OUTPUT SMCR,AUX
		SLEEP
		NOP
		NOP
		ANDI AUX,(~(1<<SE))								;CUANDO SALGO DE SLEEP, PONGO SE=0.
		OUTPUT SMCR,AUX
*/
RJMP PRUEBA
;-----------------------------------------------------------------------------------

;------------------------------MAIN_FUNCTIONS---------------------------------------
ISR_INT0:
RETI

ISR_TIMER_1_OV:
RETI

NO_SOLAR_PANEL_CONNECTED:
	INPUT AUX,BT_FLAG
	TST AUX
	BREQ SLEEP_MODE			;SI NO HAY CONEXION BT, NO MANDA NADA
	LDIW	Z,(MSJ_DISCONNECTED_PANEL*2)
	RCALL TRANSMITIR_MENSAJE
	RJMP SLEEP_MODE

AT_NIGHT:
	RCALL LIGHT_TURN_ON
	RJMP SLEEP_MODE

INT_EXT_INIT:
		
		;SETEO EL PIN INT0 (PD2) COMO ENTRADA.
		INPUT	AUX,DDRD
		ANDI	AUX,(~(1<<PD2))
		OUTPUT	DDRD,AUX

		;SETEO LA INTERRUPCION POR BAJO NIVEL.
		INPUT	AUX,EICRA
		ANDI	AUX,(~((1<<ISC00)|(1<<ISC01)))
		ORI		AUX,(1<<ISC00)|(0<<ISC01)		;SETEO PARA QUE SALTE LA INT0 SI HAY CUALQUIER CAMBIO.
		OUTPUT	EICRA,AUX
	
		;HABILITO LAS INTERRUPCION INT0.
		INPUT	AUX,EIMSK
		ANDI	AUX,~((1<<INT0)|(1<<INT1))		;SETEO INT0 E INT1 EN CERO PARA BORRAR LO QUE TENIAN ESOS BIT'S
		ORI		AUX,(1<<INT0)|(0<<INT1)			;CONFIGURO COMO QUIERO: INT0 HABILITADA E INT1 DESHABILITADA
		OUTPUT	EIMSK,AUX

RET

.include "ADC.inc"
.include "PWM.inc"
.include "SERIAL_PORT.inc"
.include "DELAY.inc"
.include "LIGHT.inc"
.include "BATTERY.inc"
.include "SOLAR_PANEL.inc"
.include "LDRS.inc"
.include "MOTORS.inc"
