;*****************************************************
;* 	Programa PWM PORTB
;*
;*  Created: 29/05/2016
;*  Autor: Joaquín Ulloa
;*	
;*	f_outPWM = f_clkIO / (prescaler * 256)
;*	Configuracion Fast Pwm
;*	
;***************************************************** 
; habria que hace un include de delays y borrar delays!!
.include "m328Pdef.inc"   	;Incluye los nombres de los registros del micro
.include "avr_macros.inc"	;Incluye los macros
.listmac					;Permite que se expandan las macros en el listado
;***************************************************** 
.DSEG						;Se abre un segmento de datos para definir variables
;La rutina usa un solo registro + los de delay
.DEF	PWM_DATA 	= R16
.EQU	PWM_DC	= 30		;Duty cicle {0,255}
.CSEG
;***************************************************** 
.ORG 0x0000				;se setean los registros de interrupciones
RJMP SETUP_PWM			;ESTO ES UNA SUB RUTINA QUE SE DEBE EJECUTAR SOLO UNA VEZ

SETUP_PWM:
;Se inicializa el stack pointer ESTO SE DEBE HACER EN EL MAIN POSTA, NO ACA
	LDI PWM_DATA,LOW(RAMEND)
	OUT SPL,PWM_DATA
	LDI	PWM_DATA,HIGH(RAMEND)
	OUT SPH,PWM_DATA
;Se inicializan como salida los pines de PWM
	INPUT PWM_DATA,DDRD
	ANDI PWM_DATA (~(0x60))	;Mascara para tocar solo B5 Y B6
	ORI PWM_DATA,((1<<DDD5)|(1<<DDD6))
	OUTPUT DDRB,PWM_DATA
;Se inicializan como Fast PWM y non-inverting mode
	;Fast PWM: WGM02=0 (por defecto), WGM01=1 y WGM00=1
	;Non-inverting mode: COM0A1=1 y COM0A0=0
	;Descripcion de registros en seccion 15.9 (pag 106-112)
	INPUT PWM_DATA,TCCR1A	;Timer/counter control register A
	ANDI PWM_DATA,(~(0xF3))	;Mascara para no tocar bits 2 y 3
	ORI PWM_DATA,((1<<COM1A1)|(1<<COM1B1)|(1<<COM1A0)|(1<<COM1B0)|(1<<WGM10)|(0<<WGM11))	;fast PWM, non-inverting
	OUTPUT TCCR1A,PWM_DATA
;Se inicializa el prescaler del PWM
	INPUT PWM_DATA,TCCR1B	;Timer/counter control register B
	;hacer mascara de forma tal que los bits 0, 1, 2 queden en 0
	ANDI PWM_DATA,(~0x1F)	;Mascara para no tocar bits 3 a 7
	ORI PWM_DATA,((0<<WGM13)|(1<<WGM12)|(0<<CS10)|(1<<CS11)|(0<<CS12))	;Prescaler = 8
	OUTPUT TCCR1B,PWM_DATA
;*****************************************************
	LDI PWM_DATA,0x00	
PWM_MAIN:	;ESTO ES UNA SUB RUTINA QUE SE DEBE EJECUTAR CADA VEZ QUE SE QUIERE CAMBIAR EL PWM
	OUTPUT OCR1AL,PWM_DATA	
	INC PWM_DATA
	RCALL DELAY
	CPI PWM_DATA,30
	BRSH PWM_RESET
RJMP PWM_MAIN

PWM_RESET:
	CLR PWM_DATA
RJMP PWM_MAIN
;*****************************************************
DELAY:	;ESTO HAY QUE PONERLO CON UN INCLUDE, NO VA ACA
; Generated by delay loop calculator
; at http://www.bretmulvey.com/avrdelay.html
; Delay 80 000 cycles
; 10ms at 8.0 MHz
    ldi  r18, 2
    ldi  r19, 56
    ldi  r20, 174
L1: dec  r20
    brne L1
    dec  r19
    brne L1
    dec  r18
    brne L1

RET				
